spring.application.name=ElderEase

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d05gnvqli9vc738pin00-a.oregon-postgres.render.com/elder_ease_db_vsv1
spring.datasource.username=root
spring.datasource.password=viuLXRdhTJbnDeoo22Nx4LLpBl7FvzEq


# Should make local development easier by having to change local host only once CHANGE AS NEEDED FOR URSELF
frontend.url=http://localhost:3001
