spring.application.name=ElderEase

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-cvdvel8gph6c73caiet0-a.oregon-postgres.render.com/elder_ease_db
spring.datasource.username=root
spring.datasource.password=kilOkBgngLvokaVyviQ7g33HBsdBAzAx
